name: tp
services:
  data_cleaner:
    container_name: data_cleaner
    image: data_cleaner:latest
    environment:
      - PYTHONUNBUFFERED=1
      - MOVIES_EXCHANGE=movies
    volumes:
      - ./controllers/data_cleaner/config.ini:/config.ini
    networks:
      - testing_net

  client:
    container_name: client
    image: client:latest
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./client/config.ini:/config.ini
      - ./datasets/movies_metadata.csv:/datasets/movies_metadata.csv
      - ./datasets/ratings.csv:/datasets/ratings.csv
      - ./datasets/credits.csv:/datasets/credits.csv
    networks:
      - testing_net
    depends_on:
      - data_cleaner

  movies_filter_produced_in_argentina_and_spain:
    container_name: movies_filter_produced_in_argentina_and_spain
    image: movies_filter:latest
    environment:
      - PYTHONUNBUFFERED=1
      - FILTER_FIELD=production_countries
      - FILTER_VALUES=["Argentina", "Spain"]
      - OUTPUT_FIELDS_SUBSET=["id", "title", "genres", "release_date"]
    networks:
      - testing_net

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
