name: tp
services:
  data_cleaner:
    container_name: data_cleaner
    image: data_cleaner:latest
    environment:
    - PYTHONUNBUFFERED=1
    - MOVIES_EXCHANGE=movies
    - RATINGS_EXCHANGE=ratings
    - CREDITS_EXCHANGE=credits
    volumes:
    - ./controllers/data_cleaner/config.ini:/config.ini
    networks:
    - testing_net
  results_handler:
    container_name: results_handler
    image: results_handler:latest
    environment:
    - PYTHONUNBUFFERED=1
    - INPUT_QUEUES=[("movies_produced_in_argentina_and_spain_released_between_2000_2009",
      "movies_produced_in_argentina_and_spain_released_between_2000_2009"), ("top_investor_countries",
      "top_investor_countries"), ("most_least_rated_movies_produced_in_argentina_released_after_2000",
      "most_least_rated_movies_produced_in_argentina_released_after_2000"), ("top_actors_participation_movies_produced_in_argentina_released_after_2000",
      "top_actors_participation_movies_produced_in_argentina_released_after_2000"),
      ("avg_rate_revenue_budget_by_sentiment", "avg_rate_revenue_budget_by_sentiment")]
    volumes:
    - ./controllers/results_handler/config.ini:/config.ini
    networks:
    - testing_net
  client_1:
    container_name: client_1
    image: client:latest
    environment:
    - PYTHONUNBUFFERED=1
    - RESULTS_DIR=/results/client_1
    volumes:
    - ./client/config.ini:/config.ini
    - ./datasets/movies_metadata.csv:/datasets/movies_metadata.csv
    - ./datasets/ratings.csv:/datasets/ratings.csv
    - ./datasets/credits.csv:/datasets/credits.csv
    - ./results/client_1:/results/client_1
    networks:
    - testing_net
    depends_on:
    - data_cleaner
    - results_handler
  client_2:
    container_name: client_2
    image: client:latest
    environment:
    - PYTHONUNBUFFERED=1
    - RESULTS_DIR=/results/client_2
    volumes:
    - ./client/config.ini:/config.ini
    - ./datasets/movies_metadata.csv:/datasets/movies_metadata.csv
    - ./datasets/ratings.csv:/datasets/ratings.csv
    - ./datasets/credits.csv:/datasets/credits.csv
    - ./results/client_2:/results/client_2
    networks:
    - testing_net
    depends_on:
    - data_cleaner
    - results_handler
  movies_filter_produced_in_argentina_and_spain_1:
    container_name: movies_filter_produced_in_argentina_and_spain_1
    image: movies_filter:latest
    environment:
    - PYTHONUNBUFFERED=1
    - FILTER_FIELD=production_countries
    - FILTER_VALUES=["Argentina", "Spain"]
    - OUTPUT_FIELDS_SUBSET=["id", "title", "genres", "release_date"]
    - INPUT_QUEUES=[("movies_q1", "movies")]
    - OUTPUT_EXCHANGE=movies_produced_in_argentina_and_spain
    - CLUSTER_SIZE=1
    - ID=1
    volumes:
    - ./controllers/movies_filter/config.ini:/config.ini
    networks:
    - testing_net
  movies_filter_released_between_2000_2009_1:
    container_name: movies_filter_released_between_2000_2009_1
    image: movies_filter:latest
    environment:
    - PYTHONUNBUFFERED=1
    - FILTER_FIELD=release_date
    - FILTER_VALUES=(2000, 2009)
    - OUTPUT_FIELDS_SUBSET=["id", "title", "genres"]
    - INPUT_QUEUES=[("movies_produced_in_argentina_and_spain", "movies_produced_in_argentina_and_spain")]
    - OUTPUT_EXCHANGE=movies_produced_in_argentina_and_spain_released_between_2000_2009
    - CLUSTER_SIZE=1
    - ID=1
    volumes:
    - ./controllers/movies_filter/config.ini:/config.ini
    networks:
    - testing_net
  movies_filter_by_one_production_country_1:
    container_name: movies_filter_by_one_production_country_1
    image: movies_filter:latest
    environment:
    - PYTHONUNBUFFERED=1
    - FILTER_FIELD=production_countries
    - FILTER_VALUES=1
    - OUTPUT_FIELDS_SUBSET=["production_countries", "budget"]
    - INPUT_QUEUES=[("movies_q2", "movies")]
    - OUTPUT_EXCHANGE=movies_produced_by_one_country
    - CLUSTER_SIZE=1
    - ID=1
    volumes:
    - ./controllers/movies_filter/config.ini:/config.ini
    networks:
    - testing_net
  top_investor_countries_calculator:
    container_name: top_investor_countries_calculator
    image: top_investor_countries_calculator:latest
    environment:
    - PYTHONUNBUFFERED=1
    - TOP_N_INVESTOR_COUNTRIES=5
    - INPUT_QUEUES=[('movies_produced_by_one_country', 'movies_produced_by_one_country')]
    - OUTPUT_EXCHANGE=top_investor_countries
    volumes:
    - ./controllers/top_investor_countries_calculator/config.ini:/config.ini
    networks:
    - testing_net
  movies_filter_produced_in_argentina_1:
    container_name: movies_filter_produced_in_argentina_1
    image: movies_filter:latest
    environment:
    - PYTHONUNBUFFERED=1
    - FILTER_FIELD=production_countries
    - FILTER_VALUES=["Argentina"]
    - OUTPUT_FIELDS_SUBSET=["id", "title", "release_date"]
    - INPUT_QUEUES=[("movies_q3_q4", "movies")]
    - OUTPUT_EXCHANGE=movies_produced_in_argentina
    - CLUSTER_SIZE=1
    - ID=1
    volumes:
    - ./controllers/movies_filter/config.ini:/config.ini
    networks:
    - testing_net
  movies_filter_released_after_2000_1:
    container_name: movies_filter_released_after_2000_1
    image: movies_filter:latest
    environment:
    - PYTHONUNBUFFERED=1
    - FILTER_FIELD=release_date
    - FILTER_VALUES=(2000,)
    - OUTPUT_FIELDS_SUBSET=["id", "title"]
    - INPUT_QUEUES=[("movies_produced_in_argentina", "movies_produced_in_argentina")]
    - OUTPUT_EXCHANGE=movies_produced_in_argentina_released_after_2000
    - CLUSTER_SIZE=1
    - ID=1
    volumes:
    - ./controllers/movies_filter/config.ini:/config.ini
    networks:
    - testing_net
  movies_router_by_id_1:
    container_name: movies_router_by_id_1
    image: router:latest
    environment:
    - PYTHONUNBUFFERED=1
    - DESTINATION_NODES_AMOUNT=1
    - INPUT_QUEUES=[("movies_produced_in_argentina_released_after_2000", "movies_produced_in_argentina_released_after_2000")]
    - OUTPUT_EXCHANGE_PREFIXES=["movies_produced_in_argentina_released_after_2000_q3",
      "movies_produced_in_argentina_released_after_2000_q4"]
    - CLUSTER_SIZE=1
    - ID=1
    volumes:
    - ./controllers/router/config.ini:/config.ini
    networks:
    - testing_net
  ratings_router_by_movie_id_1:
    container_name: ratings_router_by_movie_id_1
    image: router:latest
    environment:
    - PYTHONUNBUFFERED=1
    - DESTINATION_NODES_AMOUNT=1
    - INPUT_QUEUES=[("ratings", "ratings")]
    - OUTPUT_EXCHANGE_PREFIXES=["ratings"]
    - CLUSTER_SIZE=3
    - ID=1
    volumes: &id001
    - ./controllers/router/config.ini:/config.ini
    networks: &id002
    - testing_net
  ratings_router_by_movie_id_2:
    container_name: ratings_router_by_movie_id_2
    image: router:latest
    environment:
    - PYTHONUNBUFFERED=1
    - DESTINATION_NODES_AMOUNT=1
    - INPUT_QUEUES=[("ratings", "ratings")]
    - OUTPUT_EXCHANGE_PREFIXES=["ratings"]
    - CLUSTER_SIZE=3
    - ID=2
    volumes: *id001
    networks: *id002
  ratings_router_by_movie_id_3:
    container_name: ratings_router_by_movie_id_3
    image: router:latest
    environment:
    - PYTHONUNBUFFERED=1
    - DESTINATION_NODES_AMOUNT=1
    - INPUT_QUEUES=[("ratings", "ratings")]
    - OUTPUT_EXCHANGE_PREFIXES=["ratings"]
    - CLUSTER_SIZE=3
    - ID=3
    volumes: *id001
    networks: *id002
  movies_ratings_joiner_1:
    container_name: movies_ratings_joiner_1
    image: movies_joiner:latest
    environment:
    - PYTHONUNBUFFERED=1
    - INPUT_QUEUES=[("movies_produced_in_argentina_released_after_2000_q3_1", "movies_produced_in_argentina_released_after_2000_q3_1"),
      ("ratings_1", "ratings_1")]
    - OUTPUT_EXCHANGE=ratings_movies_produced_in_argentina_released_after_2000
    - CLUSTER_SIZE=1
    - ID=1
    volumes:
    - ./controllers/movies_joiner/config.ini:/config.ini
    networks:
    - testing_net
  most_least_rated_movies_calculator:
    container_name: most_least_rated_movies_calculator
    image: most_least_rated_movies_calculator:latest
    environment:
    - PYTHONUNBUFFERED=1
    - INPUT_QUEUES=[('ratings_movies_produced_in_argentina_released_after_2000', 'ratings_movies_produced_in_argentina_released_after_2000')]
    - OUTPUT_EXCHANGE=most_least_rated_movies_produced_in_argentina_released_after_2000
    volumes:
    - ./controllers/most_least_rated_movies_calculator/config.ini:/config.ini
    networks:
    - testing_net
  credits_router_by_movie_id_1:
    container_name: credits_router_by_movie_id_1
    image: router:latest
    environment:
    - PYTHONUNBUFFERED=1
    - DESTINATION_NODES_AMOUNT=1
    - INPUT_QUEUES=[("credits", "credits")]
    - OUTPUT_EXCHANGE_PREFIXES=["credits"]
    - CLUSTER_SIZE=2
    - ID=1
    volumes: &id003
    - ./controllers/router/config.ini:/config.ini
    networks: &id004
    - testing_net
  credits_router_by_movie_id_2:
    container_name: credits_router_by_movie_id_2
    image: router:latest
    environment:
    - PYTHONUNBUFFERED=1
    - DESTINATION_NODES_AMOUNT=1
    - INPUT_QUEUES=[("credits", "credits")]
    - OUTPUT_EXCHANGE_PREFIXES=["credits"]
    - CLUSTER_SIZE=2
    - ID=2
    volumes: *id003
    networks: *id004
  movies_credits_joiner_1:
    container_name: movies_credits_joiner_1
    image: movies_joiner:latest
    environment:
    - PYTHONUNBUFFERED=1
    - INPUT_QUEUES=[("movies_produced_in_argentina_released_after_2000_q4_1", "movies_produced_in_argentina_released_after_2000_q4_1"),
      ("credits_1", "credits_1")]
    - OUTPUT_EXCHANGE=credits_movies_produced_in_argentina_released_after_2000
    - CLUSTER_SIZE=1
    - ID=1
    volumes:
    - ./controllers/movies_joiner/config.ini:/config.ini
    networks:
    - testing_net
  top_actors_participation_calculator:
    container_name: top_actors_participation_calculator
    image: top_actors_participation_calculator:latest
    environment:
    - PYTHONUNBUFFERED=1
    - TOP_N_ACTORS_PARTICIPATION=10
    - INPUT_QUEUES=[('credits_movies_produced_in_argentina_released_after_2000', 'credits_movies_produced_in_argentina_released_after_2000')]
    - OUTPUT_EXCHANGE=top_actors_participation_movies_produced_in_argentina_released_after_2000
    volumes:
    - ./controllers/top_actors_participation_calculator/config.ini:/config.ini
    networks:
    - testing_net
  movies_sentiment_analyzer_1:
    container_name: movies_sentiment_analyzer_1
    image: movies_sentiment_analyzer:latest
    environment:
    - PYTHONUNBUFFERED=1
    - FIELD_TO_ANALYZE=overview
    - INPUT_QUEUES=[("movies_q5", "movies")]
    - OUTPUT_EXCHANGE=movies_sentiment_analyzed
    - CLUSTER_SIZE=1
    - ID=1
    volumes:
    - ./controllers/movies_sentiment_analyzer/config.ini:/config.ini
    networks:
    - testing_net
  avg_rate_revenue_budget_calculator:
    container_name: avg_rate_revenue_budget_calculator
    image: avg_rate_revenue_budget_calculator:latest
    environment:
    - PYTHONUNBUFFERED=1
    - INPUT_QUEUES=[('movies_sentiment_analyzed', 'movies_sentiment_analyzed')]
    - OUTPUT_EXCHANGE=avg_rate_revenue_budget_by_sentiment
    volumes:
    - ./controllers/avg_rate_revenue_budget_calculator/config.ini:/config.ini
    networks:
    - testing_net
  health_guard_1:
    container_name: health_guard_1
    image: health_guard:latest
    environment:
    - PYTHONUNBUFFERED=1
    - PYTHONHASHSEED=0
    - COMPOSE_PROJECT_NAME=tp
    - DONT_GUARD_CONTAINERS=["rabbitmq", "client"]
    - SERVICE_PREFIX=health_guard
    - CLUSTER_SIZE=2
    - ID=1
    volumes: &id005
    - /var/run/docker.sock:/var/run/docker.sock
    - ./health_guard/config.ini:/config.ini
    networks: &id006
    - testing_net
  health_guard_2:
    container_name: health_guard_2
    image: health_guard:latest
    environment:
    - PYTHONUNBUFFERED=1
    - PYTHONHASHSEED=0
    - COMPOSE_PROJECT_NAME=tp
    - DONT_GUARD_CONTAINERS=["rabbitmq", "client"]
    - SERVICE_PREFIX=health_guard
    - CLUSTER_SIZE=2
    - ID=2
    volumes: *id005
    networks: *id006
networks:
  testing_net:
    ipam:
      driver: default
      config:
      - subnet: 172.25.125.0/24
